version: "3"
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: jasper
      POSTGRES_DB: prisma-test
      POSTGRES_USER: jasper
    ports:
      - "5434:5432"
volumes:
  db_data:
